<a href="https://colab.research.google.com/github/NadineAppiah/lab-4-llm-decision-support/blob/main/lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#part 0
import os
from google.colab import userdata
from openai import OpenAI

API_KEY = userdata.get('GROQ_API_KEY')
if not API_KEY:
  raise ValueError("GROQ_API_KEY not found in environment variables")
print('API key loaded successfully.')

client = OpenAI(
    api_key=API_KEY,
    base_url="https://api.groq.com/openai/v1"
)

MODEL = "llama-3.3-70b-versatile"
print("client ready")

API key loaded successfully.
client ready

In [2]:
#part 1.1
def ask_llm(
    user_prompt,
    system_prompt="You are a helpful assistant.",
    temperature=0.7,
    max_tokens=500
):
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        temperature=temperature,
        max_tokens=max_tokens
    )

    return response.choices[0].message.content
print(ask_llm("What is artificial intelligence?"))

Artificial intelligence (AI) refers to the development of computer systems that can perform tasks that typically require human intelligence, such as:

1. **Learning**: AI systems can learn from data and improve their performance over time.
2. **Problem-solving**: AI systems can analyze situations, identify patterns, and make decisions to solve problems.
3. **Reasoning**: AI systems can draw inferences, make predictions, and arrive at conclusions based on available data.
4. **Perception**: AI systems can interpret and understand data from sensors, such as images, speech, and text.

The goal of AI is to create systems that can think and act like humans, but with the ability to process and analyze large amounts of data much faster and more accurately than humans.

There are several types of AI, including:

1. **Narrow or Weak AI**: Designed to perform a specific task, such as facial recognition, language translation, or playing chess.
2. **General or Strong AI**: A hypothetical AI system that possesses human-like intelligence and can perform any intellectual task that a human can.
3. **Superintelligence**: An AI system that is significantly more intelligent than the best human minds, potentially leading to significant advancements or risks.

AI has many applications in various fields, including:

1. **Virtual assistants**: Siri, Alexa, and Google Assistant
2. **Image and speech recognition**: Self-driving cars, facial recognition systems, and voice-controlled devices
3. **Natural Language Processing (NLP)**: Chatbots, language translation software, and text analysis tools
4. **Predictive analytics**: Forecasting stock prices, predicting customer behavior, and identifying potential risks

Overall, artificial intelligence has the potential to revolutionize many aspects of our lives, from healthcare and education to transportation and entertainment.

**Anatomy of a call**

1. The system role provides instructions that define the LLM's behavior, purpose, or style, while the user role contains the specific request or question from the user. For example, a system message could tell the model to act as a financial decision-support assistant, while the user message could ask it to evaluate a customer's loan application.

2. A token is a small unit of text that an LLM processes. Words, parts of words, and punctuation can each form tokens. API providers charge based on tokens because longer inputs and outputs require more computational resources than shorter ones, so token usage is a better measure of the work performed than simply counting requests.

In [3]:
#part 1.2
question = "Suggest a name for a savings product for market traders in Accra."

print("====TEMPERATURE 0.0====")

for i in range(5):
  response = ask_llm(question, temperature=0.0, max_tokens=100)
  print(f"Response {i + 1}:")
  print(response)

print("====TEMPERATURE 1.2====")

for i in range(5):
  response = ask_llm(question, temperature=1.2, max_tokens=100)
  print(f"Response {i + 1}:")
  print(response)

====TEMPERATURE 0.0====
Response 1:
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Traders' Treasure**: This name emphasizes the idea of saving and accumulating wealth, which is a key goal for market traders.
3. **Accra Market Fund**: This name is straightforward and clearly communicates the product's purpose and target audience.
4.
Response 2:
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Trader's Treasure**: This name emphasizes the idea of saving and accumulating wealth.
3. **Accra Amanfu**: "Amanfu" is a Ghanaian word for "savings" or "treasury", so this name incorporates local language
Response 3:
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Trader's Treasure**: This name emphasizes the idea of saving and accumulating wealth.
3. **Sika Kokoo**: "Sika" means "money" in the Akan language, and "Kokoo" means "gather" or "collect
Response 4:
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Trader's Treasure**: This name emphasizes the idea of saving and accumulating wealth, which could appeal to market traders.
3. **Sika Souce**: "Sika" means "money" in the Akan language, which is widely spoken in Ghana
Response 5:
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Traders' Treasure**: This name emphasizes the idea of saving and accumulating wealth, which is a key goal for market traders.
3. **Accra Market Fund**: This name is straightforward and clearly communicates the product's purpose and target audience.
4.
====TEMPERATURE 1.2====
Response 1:
Considering the target audience are market traders in Accra, I'd suggest a name that reflects the local culture, financial goals, and aspirations of the traders. Here are a few ideas:

1. **Sika Kokoo**: "Sika" means money in the Akan language, and "Kokoo" means gathering or collection. This name emphasizes the idea of gathering savings.
2. **MarketMmoa**: "Mmoa" means savings or treasure in the Akan language.
Response 2:
Here are a few suggestions for a savings product tailored to market traders in Accra:

1. **Makola Save**: "Makola" is a reference to the famous Makola Market in Accra, which is a hub for market traders. This name is catchy and instantly relatable to the target audience.
2. **Market Booster**: This name suggests that the savings product will help market traders boost their businesses and increase their savings.
3. **TradeWise**: This name conveys
Response 3:
For a savings product targeting market traders in Accra, here are a few suggestions:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name immediately resonates with the target audience.
2. **Trader's Treasure**: This name plays on the idea of savings being a valuable treasure, which is likely to appeal to market traders.
3. **Sika Sokoo**: "Sika" means "money" in the Ghanaian language
Response 4:
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Traders' Treasure**: This name emphasizes the idea of saving and storing valuables, which is perfect for a savings product.
3. **Acepa Account**: "Acepa" is a Ga word that means "to save" or "to keep
Response 5:
Here are some name suggestions for a savings product tailored to market traders in Accra:

1. **Makola Savings**: "Makola" is a well-known market in Accra, making this name relatable and familiar to market traders.
2. **Trader's Treasure**: This name conveys the idea of saving and accumulating wealth, which is appealing to traders looking to grow their businesses.
3. **SokoSave**: "Soko" means "market" in Ghanaian Pid

**Temperature**

1. At temperature 0.0, the responses were generally more consistent and similar to one another. At temperature 1.2, the responses showed greater variation and creativity. For a loan decision-support system, a low temperature such as 0.0-0.3 would be more appropriate because the system should produce consistent and predictable responses rather than highly random recommendations. The final loan decision should also be based on defined financial criteria rather than creativity.

In [4]:
#part 2
LETTERS = {
"L001": """Dear Sir/Madam,
My name is Akosua Mensah and I have been selling provisions at Makola Market for 12 years.
I am applying for a loan of GHS 8,000 to buy a deep freezer and expand into frozen foods.
My current stall makes about GHS 900 profit each month. I have saved GHS 2,500 with your
susu scheme over the past two years and I have never missed a contribution. I can repay
GHS 450 monthly over 20 months. My sister, a teacher, will stand as my guarantor.
Thank you for considering my application.""",

"L002": """Hello,
I am Kwame Boateng, a commercial driver in Kumasi. I need GHS 25,000 urgently to repair my
trotro engine and settle some personal debts. Business has been slow but it will surely
pick up after the festive season. I can pay back whenever the money comes. I do not have
collateral at the moment but God willing everything will be fine. Please help me quickly.""",

"L003": """Dear Loan Committee,
I am Efua Darko, owner of Darko Fashions, a registered dressmaking business in Takoradi
(registration no. BN-2019-4482). I employ three apprentices. I request GHS 15,000 to
purchase two industrial sewing machines and fabric stock ahead of the Christmas season.
Last year my December revenue alone was GHS 22,000; monthly profit averages GHS 2,800.
I hold a fixed deposit of GHS 5,000 with GCB which I can pledge. Proposed repayment:
GHS 1,100 monthly for 15 months. Attached are my sales records for the past 18 months.""",

"L004": """Good day,
My name is Yaw Owusu. I want a loan for my poultry farm at Nsawam. The amount is GHS 12,000
for feed and 500 new layers. I started the farm last year. Sometimes I make good money,
around GHS 1,500 in a good month, but bird flu affected us in March and I lost many birds.
I am rebuilding now. I can repay in 18 months. My uncle has agreed to guarantee the loan
with his taxi.""",

"L005": """Dear Manager,
I am writing on behalf of the Adenta Women's Weaving Cooperative (14 members). We seek
GHS 30,000 to buy a bulk order of yarn directly from the factory, cutting out middlemen and
raising our margins from 15% to about 35%. The cooperative has operated for 6 years and
holds GHS 9,000 in our group account. We propose repayment of GHS 2,000 monthly over
16 months, backed by our group savings and joint liability agreement.""",

"L006": """Hi,
This is Kofi. I saw your advert. I want GHS 50,000 to start a car washing business, a
provision shop, and also import phones from Dubai. I am 22 and full of energy. I have not
started any of these yet but my friends say I am very business minded. I will pay back in
one year when the businesses are booming. No collateral but I am trustworthy.""",
}

GOLD = {
  "L001": {"applicant_name": "Akosua Mensah", "amount_ghs": 8000,  "purpose": "buy deep freezer / expand into frozen foods",
           "monthly_profit_ghs": 900,  "has_collateral_or_guarantor": True,  "repayment_months": 20},
  "L003": {"applicant_name": "Efua Darko",    "amount_ghs": 15000, "purpose": "industrial sewing machines and fabric stock",
           "monthly_profit_ghs": 2800, "has_collateral_or_guarantor": True,  "repayment_months": 15},
  "L006": {"applicant_name": "Kofi",          "amount_ghs": 50000, "purpose": "car wash, provision shop, phone imports",
           "monthly_profit_ghs": None, "has_collateral_or_guarantor": False, "repayment_months": 12},
}

print(f"{len(LETTERS)} letters loaded.")

6 letters loaded.

In [5]:
#part 3.1
SUMMARY_PROMPT_V1 = "Summarize this:"

for letter_id in ['L002', 'L006']:
  response = ask_llm(f"{SUMMARY_PROMPT_V1} {LETTERS[letter_id]}",
                     temperature = 0.7, max_tokens = 200)
  print(f"Letter {letter_id}:")
  print(response)

SUMMARY_SYSTEM_PROMPT_V2 = """
You are an assistant to a microfinance loan officer.
Summarise loan applications into a brief summary that a busy loan officer can quickly scan.

Requirements:
-Write 3-4 sentences.
-Be factual and neutral.
-Include applicants business and loan purpose.
-Include repayment plan.
-Include collateral, guarantor, savings, and important financial information.
-Do not invent, assume, or infer information that is not stated in the letter.
-Do not make approval or rejection decisions on behalf of the loan officer.
"""

SUMMARY_PROMPT_V2 = "Summarize this letter into a brief summary:"

for letter_id in ['L002', 'L006']:
  user_prompt = f"{SUMMARY_PROMPT_V2} {LETTERS[letter_id]}"

  response = ask_llm(user_prompt,system_prompt = SUMMARY_SYSTEM_PROMPT_V2,
                     temperature = 0, max_tokens=200)
  print("\n---V1---")
  print(f"Letter {letter_id}:")
  print(response)

for letter_id in ["L002", "L006"]:
  response_v1 = ask_llm(f"{SUMMARY_PROMPT_V1} {LETTERS[letter_id]}",
                      temperature = 0.7, max_tokens=200)
  print(f"Letter {letter_id}:")
  print(response_v1)

  response_v2 = ask_llm(f"{SUMMARY_PROMPT_V2} {LETTERS[letter_id]}",
                      temperature = 0, max_tokens=200)
  print("\n---V2---")
  print(f"Letter {letter_id}:")
  print(response_v2)

Letter L002:
Kwame Boateng, a commercial driver from Kumasi, is urgently seeking GHS 25,000 to repair his vehicle's engine and pay off personal debts. He's experiencing a slow business period but expects things to improve after the festive season and is willing to repay the loan when his finances allow. However, he doesn't have any collateral to offer at the moment.
Letter L006:
Kofi, a 22-year-old, is seeking a loan of GHS 50,000 to start three businesses: a car washing service, a provision shop, and a phone import business from Dubai. He has no experience or collateral, but claims to be "business-minded" and promises to repay the loan in one year when his businesses are successful, relying on his personal trustworthiness.

---V1---
Letter L002:
Kwame Boateng, a commercial driver, is applying for a GHS 25,000 loan to repair his trotro engine and settle personal debts. He intends to repay the loan from his business income, expecting an increase in earnings after the festive season. However, he does not have collateral to secure the loan. The applicant's repayment plan is informal, stating he can pay back "whenever the money comes", with no specific guarantor, savings, or financial details provided.

---V1---
Letter L006:
Kofi, a 22-year-old, is applying for a GHS 50,000 loan to start a car washing business, a provision shop, and a phone import business. The loan purpose is to fund the initial setup of these ventures. Kofi plans to repay the loan in one year, expecting the businesses to be profitable by then. He does not have collateral to offer, but claims to be trustworthy, and has not provided any information on a guarantor, savings, or other financial details.
Letter L002:
Kwame Boateng, a commercial driver from Kumasi, is requesting a loan of GHS 25,000 to repair his vehicle's engine and pay off personal debts. He's experiencing a slow period in business, but expects it to improve after the festive season. He doesn't have collateral, but promises to repay the loan as soon as possible.

---V2---
Letter L002:
Kwame Boateng, a commercial driver, is requesting GHS 25,000 to repair his vehicle's engine and settle debts, promising to repay when business improves after the festive season.
Letter L006:
Kofi, a 22-year-old, is seeking a loan of GHS 50,000 to start three businesses: a car washing service, a provision shop, and a phone import business from Dubai. He has no prior experience, but claims to be "business-minded" based on his friends' opinions. He promises to repay the loan within a year, once his businesses are successful, and offers his trustworthiness as assurance, as he has no collateral to provide.

---V2---
Letter L006:
Kofi, a 22-year-old, is seeking GHS 50,000 to start three businesses: a car washing service, a provision shop, and a phone import business. He claims to be business-minded and promises to repay the loan within a year, without offering any collateral, relying on his trustworthiness.

**Summarisation prompt**

1. V1 produced a general summary but did not explicitly instruct the model to focus on information important to a loan officer. V2 was more focused because it required the summary to include the applicant's business, loan purpose, financial information, repayment information, and collateral or guarantor information. V2 was also more consistent in length because it explicitly required 3-4 sentences and instructed the model to remain factual and neutral.
2. "No invented details" is essential because the system must base its output only on information actually provided by the applicant. Inventing financial information, collateral, income, or other facts could mislead the loan officer and affect an important financial decision. This type of failure is commonly called an LLM hallucination.

In [ ]:
#part 3.2
import json
import pandas as pd

EXTRACT_PROMPT = """
You are a data extraction assistant for a microfinance institution.

Extract information from the loan application letter and return only
a valid JSON object.

The JSON object must contain EXACTLY these keys:
{
    "applicant_name": "string",
    "amount_ghs": number,
    "purpose": "string",
    "monthly_profit_ghs": number or null,
    "has_collateral_or_guarantor": boolean,
    "repayment_months": number or null}

Rules:
1. Extract information only from the letter.
2. If a field is not stated in the letter, use null.
3. Do not invent, assume, or infer information.
4. amount_ghs must be a number, not a string.
5. monthly_profit_ghs must be a number or null.
6. has_collateral_or_guarantor must be true or false.
7. repayment_months must be a number or null.
8. Return ONLY the JSON object.
9. Do not include explanations or introductions.
10. Do not use Markdown code fences.
11. The first character of your response must be { and the last
    character must be }.

Worked example:
Loan Application Letter:
"Dear Manager,
My name is Ama Addo. I run a small fruit stall in Accra.
I am requesting GHS 6,000 to purchase a refrigerator and more stock.
My average monthly profit is GHS 700. My brother will guarantee the loan.
I will repay the loan over 12 months."

Correct JSON:
{
    "applicant_name": "Ama Addo",
    "amount_ghs": 6000,
    "purpose": "refrigerator and more stock",
    "monthly_profit_ghs": 700,
    "has_collateral_or_guarantor": true,
    "repayment_months": 12}
"""

EXTRACT_USER_PROMPT = """
Extract the required fields from this loan application:
{letter_text}
"""

def extract_fields(letter_text, temperature = 0):
    response = ask_llm(
        EXTRACT_USER_PROMPT.format(letter_text=letter_text),
        system_prompt=EXTRACT_PROMPT,
        temperature=temperature,
        max_tokens=300
    )

    result = response.choices[0].message.content.strip()

    if result.startswith("```json"):
        result = result[7:]

    if result.startswith("```"):
        result = result[3:]

    if result.endswith("```"):
        result = result[:-3]

    result = result.strip()

    start = result.find("{")
    end = result.rfind("}")

    if start != -1 and end != -1:
        result = result[start:end + 1]

    try:
        return json.loads(result)

    except json.JSONDecodeError:
        print(f"Error decoding JSON: {result}")
        return None

results = []

for letter_id, letter_text in LETTERS.items():
    extracted = extract_fields(letter_text)
    if extracted is not None:
        extracted["letter_id"] = letter_id
        results.append(extracted)

df = pd.DataFrame(results)
df

,applicant_name,amount_ghs,purpose,monthly_profit_ghs,has_collateral_or_guarantor,repayment_months,letter_id
0,Akosua Mensah,8000,buy a deep freezer and expand into frozen foods,900.0,True,20.0,L001
1,Kwame Boateng,25000,repair my trotro engine and settle some person...,NaN,False,NaN,L002
2,Efua Darko,15000,purchase two industrial sewing machines and fa...,2800.0,True,15.0,L003
3,Yaw Owusu,12000,feed and 500 new layers,1500.0,True,18.0,L004
4,Adenta Women's Weaving Cooperative,30000,buy a bulk order of yarn,NaN,True,16.0,L005
5,Kofi,50000,"start a car washing business, a provision shop...",NaN,False,12.0,L006

**Structured extraction**

1. The few-shot example should not come from the six letters because using one of the evaluation letters could make the prompt specifically tailored to that data. This could give the model information about the expected answers and make the evaluation less representative of how well the extraction system generalizes to unseen applications.
2. "Use null, do not guess" prevents the model from filling missing information with assumptions. Without this instruction, an LLM may generate plausible-looking values that were never provided in the letter. This is especially problematic in loan applications because invented financial information could mislead the loan officer.
3. Temperature 0 is appropriate for extraction because we want consistent and predictable outputs rather than creative variations. The task is to accurately extract information that already exists in the letter, not to generate new content. Higher temperatures are more appropriate for tasks where creativity and variety are desired.

In [ ]:
#part 3.3
BRIEF_PROMPT = """
You are an assistant supporting a microfinance loan officer.

Your role is to organize information and highlight factors that a human
loan officer should consider. You must NOT make the final loan decision.

Using the loan application letter and the extracted information, produce
a concise decision-support brief with exactly these four sections:

1. Strengths
- List positive factors that are explicitly supported by the letter.
- Use bullet points.

2. Risks / Red Flags
- List potential concerns or risks supported by the letter.
- Use bullet points.
- Do not invent risks that are not supported by the information provided.

3. Missing Information
- List important information or documents that the loan officer should
  request before making a decision.
- Use bullet points.

4. Suggested Next Step
- Suggest an appropriate action for the loan officer, such as:
  "request documents", "invite for interview", or "flag for senior review".
- Do NOT say "approve" or "reject".

Important:
- Base the brief only on the information provided.
- Do not invent facts.
- Do not make assumptions about the applicant.
- The final lending decision must be made by a human loan officer.
- Keep the brief concise and professional.

"""

def generate_brief(letter_text, extracted):
    user_prompt = f"""
    Loan Application Letter:
    {letter_text}

    Extracted Information:
    {json.dumps(extracted, indent=2)}
    """

    response = ask_llm(
        user_prompt,
        system_prompt=BRIEF_PROMPT,
        temperature=0,
        max_tokens=300
    )

    return response.choices[0].message.content

briefs = {}
for letter_id, letter_text in LETTERS.items():
    extracted = extract_fields(letter_text)
    if extracted is not None:
      brief = generate_brief(letter_text, extracted)
      briefs[letter_id] = brief

for letter_id in ["L001","L002", "L006"]:
  print(f"Letter {letter_id}:")
  print(briefs[letter_id])

Letter L001:
## 1. Strengths
* The applicant has 12 years of experience selling provisions at Makola Market.
* The applicant has a stable monthly profit of GHS 900.
* The applicant has saved GHS 2,500 with the susu scheme over two years without missing a contribution.
* The applicant has a guarantor, her sister, who is a teacher.
* The applicant has a clear repayment plan of GHS 450 monthly over 20 months.

## 2. Risks / Red Flags
* The applicant is requesting a loan that is significantly larger than her monthly profit, which may pose a repayment risk.
* The expansion into frozen foods may come with additional operational risks and costs.

## 3. Missing Information
* Detailed business plan and market analysis for the expansion into frozen foods.
* Information about the applicant's sister, the guarantor, such as her income and employment stability.
* Collateral or asset information to secure the loan.
* Credit history and other debt obligations of the applicant.

## 4. Suggested Next Step
Request additional documents and information, including a detailed business plan, guarantor's employment and income verification, and collateral or asset information, to further assess the loan application.
Letter L002:
**Decision-Support Brief**

1. **Strengths**
* The applicant has a clear purpose for the loan, which is to repair his trotro engine and settle personal debts.
* The applicant is expecting an increase in business after the festive season, which could potentially improve his repayment ability.

2. **Risks / Red Flags**
* The applicant's business has been slow, which may impact his ability to repay the loan.
* The applicant does not have collateral or a guarantor, which increases the risk of the loan.
* The applicant does not have a clear repayment plan, stating he can pay back "whenever the money comes".

3. **Missing Information**
* Monthly profit or income statement to assess the applicant's repayment ability.
* Detailed breakdown of the expenses for repairing the trotro engine.
* Information on the applicant's personal debts and their impact on his financial situation.
* Repayment plan or proposed repayment schedule.

4. **Suggested Next Step**
Request additional financial information and a detailed repayment plan from the applicant to further assess his creditworthiness and ability to repay the loan.
Letter L006:
## 1. Strengths
* The applicant, Kofi, is young and full of energy, which could be beneficial for starting and managing new businesses.
* Kofi has multiple business ideas, indicating potential for diversification and risk management.
* The applicant is confident in their business abilities, as supported by their friends' opinions.

## 2. Risks / Red Flags
* The applicant has no prior experience in starting or running a business.
* There is no collateral or guarantor to secure the loan.
* The repayment plan relies on the businesses booming within a year, which is uncertain.
* The applicant lacks a proven track record of business success.

## 3. Missing Information
* Detailed business plans for the car washing business, provision shop, and phone import business.
* Projected monthly profits for each business venture.
* Information on the applicant's education, skills, and experience relevant to the proposed businesses.
* Market research and analysis to support the viability of the businesses.

## 4. Suggested Next Step
Request additional documents and information, including business plans, financial projections, and market research, to further assess the applicant's creditworthiness and the viability of the proposed businesses.

part 3.4
Commit hash:
cfed0a2

In [ ]:
#part 4.1

fields = [
    "applicant_name",
    "amount_ghs",
    "purpose",
    "monthly_profit_ghs",
    "has_collateral_or_guarantor",
    "repayment_months"
]

rows = []
for field in fields:
    row = {"field": field}
    correct = 0

    for letter_id in ["L001", "L003", "L006"]:
        extracted_row = df[df["letter_id"] == letter_id]

        if extracted_row.empty:
            extracted_value = None

        else:
            extracted_value = extracted_row.iloc[0][field]
        gold_value = GOLD[letter_id][field]

        if field == "applicant_name":
            match = (
                str(extracted_value).strip().lower()
                == str(gold_value).strip().lower()
            )
        else:
            match = extracted_value == gold_value
        row[letter_id] = "✓ " if match else "X"

        if match:
            correct += 1
    row["accuracy"] = f"{correct}/3 ({correct/3:.1%})"
    rows.append(row)

accuracy_df = pd.DataFrame(rows)

accuracy_df

                         field L001 L003 L006      accuracy
0               applicant_name   ✓    ✓    ✓   3/3 (100.0%)
1                   amount_ghs   ✓    ✓    ✓   3/3 (100.0%)
2                      purpose    X    X    X    0/3 (0.0%)
3           monthly_profit_ghs   ✓    ✓     X   2/3 (66.7%)
4  has_collateral_or_guarantor   ✓    ✓    ✓   3/3 (100.0%)
5             repayment_months   ✓    ✓    ✓   3/3 (100.0%)

In [ ]:
#part 4.2
def reliability_test(letter_id, temperature, runs=5):
    results = []
    for i in range(runs):
        result = extract_fields(LETTERS[letter_id])
        results.append(result)

    valid_results = [r for r in results if r is not None]
    result_strings = [
        json.dumps(r, sort_keys=True)
        for r in valid_results
    ]
    unique_results = set(result_strings)

    return {
        "temperature": temperature,
        "valid_json": len(valid_results),
        "identical_values": len(unique_results) == 1,
        "unique_outputs": len(unique_results),
        "results": results
    }
results_temp0 = []

for i in range(5):
    result = extract_fields(LETTERS["L004"], temperature=0)
    results_temp0.append(result)

results_temp1 = []
for i in range(5):
    result = extract_fields(LETTERS["L004"], temperature=1.0)
    results_temp1.append(result)

valid_temp0 = [r for r in results_temp0 if r is not None]
valid_temp1 = [r for r in results_temp1 if r is not None]

unique_temp0 = set(
    json.dumps(r, sort_keys=True)
    for r in valid_temp0
)
unique_temp1 = set(
    json.dumps(r, sort_keys=True)
    for r in valid_temp1
)
print("Temperature 0.0")
print(f"Valid JSON: {len(valid_temp0)}/5")
print(f"Unique outputs: {len(unique_temp0)}")
print(f"Identical across runs: {len(unique_temp0) == 1}")

print("\nTemperature 1.0")
print(f"Valid JSON: {len(valid_temp1)}/5")
print(f"Unique outputs: {len(unique_temp1)}")
print(f"Identical across runs: {len(unique_temp1) == 1}")

Temperature 0.0
Valid JSON: 5/5
Unique outputs: 1
Identical across runs: True

Temperature 1.0
Valid JSON: 5/5
Unique outputs: 1
Identical across runs: True

In [ ]:
#part 4.3
hallucination_question = """
What is the applicant's credit score?
If it is not provided, clearly state that the credit score is not provided.
"""
response = ask_llm(
    f"{hallucination_question}\n\nLoan Application:\n{LETTERS['L001']}",
    system_prompt=SUMMARY_SYSTEM_PROMPT_V2,
    temperature=0,
    max_tokens=300
)
test1_output = response.choices[0].message.content
print(test1_output)

weather_text = """
Today's weather forecast is partly cloudy with temperatures around
28 degrees Celsius. There may be light rain in the afternoon.
Winds will be moderate from the southwest.
"""

result = extract_fields(weather_text, temperature=0)
print(result)

Here is a brief summary of the loan application:
Akosua Mensah is applying for a loan of GHS 8,000 to purchase a deep freezer and expand her provision business at Makola Market into frozen foods. She plans to repay the loan with monthly installments of GHS 450 over 20 months. The applicant has GHS 2,500 in savings with the susu scheme and her sister, a teacher, will serve as her guarantor. The credit score is not provided.
{'applicant_name': None, 'amount_ghs': None, 'purpose': None, 'monthly_profit_ghs': None, 'has_collateral_or_guarantor': None, 'repayment_months': None}

**Evaluation results**
1. The extraction system achieved an overall accuracy of 72.2% (13 out of 18 fields correct). The hardest field was purpose, with an accuracy of 0%. This happened because the model often extracted the purpose using different wording from the gold-standard labels, even when the meaning was similar. For example, the gold label may say "industrial sewing machines and fabric stock," while the model may include additional words such as "purchase two" or "buy."
2. Lower temperature generally provides more consistent outputs, which is desirable for structured extraction in production. Higher temperature introduces more variation and is therefore less appropriate for deterministic extraction tasks.
3. The system did not hallucinate in either of the two tests. When asked for a credit score that was not provided, the summarizer stated that the information was unavailable. When given an irrelevant weather report, the extractor returned null for all fields rather than fabricating information. This suggests that instructions such as "do not guess," "do not invent information," and "use null when information is missing" helped reduce hallucination risk. In a production system, this could be further reduced through strict JSON validation, low temperature settings, input validation, and human review of important outputs.

part 4.4
**Appropriateness**
1. Applicants who write poorly in English or have limited formal education could be unfairly harmed. A good business could appear less credible simply because the applicant's letter is poorly written or lacks formal language. Applicants who use local expressions or have less formal documentation could also be disadvantaged. Therefore, the system should not use writing quality as a substitute for creditworthiness, and final decisions should remain with human loan officers.
2. Loan letters may contain personal and financial information, so sending them to a third-party API creates privacy and data-protection risks. Before deployment, the institution should check where the data is processed and stored, whether the provider retains or uses the data, who can access it, how the data is encrypted, and whether cross-border data transfers comply with applicable Ghanaian data-protection requirements. The institution should also have appropriate agreements and policies governing the handling of customer data.
3. i. Mandatory human review:
The LLM should only provide summaries, extracted information, risks, and suggested next steps. A qualified loan officer must verify the information and make the final lending decision.
ii. Continuous monitoring and audit logging:
The system should securely record its outputs and errors so that the institution can monitor accuracy, hallucinations, and potential unfair patterns over time. Regular reviews should be conducted to identify and correct problems.

**Reflection**
1. Iterating on a prompt is similar to tuning model hyperparameters because both involve changing inputs to improve the quality and reliability of the model's output. For example, changing temperature affects how consistent the model is, while changing the prompt affects what information the model focuses on and how it responds. The difference is that hyperparameters control the model's generation behavior, whereas prompt engineering changes the instructions and context given to the model.
2. I would not trust this system to run completely unattended. The result that most influenced my decision was the 72.2% extraction accuracy, particularly the 0% accuracy for the purpose field. Although the system performed well in the hallucination tests, a system used for financial decisions needs higher reliability and human oversight. The LLM should therefore support loan officers rather than replace them.
3. Based on the token usage from my API calls, processing 1,000 applications would require approximately 423,000 tokens per month. This shows that token usage and API pricing are important when choosing a provider. At this scale, I would compare providers based on cost per token, model quality, rate limits, reliability, privacy, and data-handling policies rather than choosing solely based on the cheapest option.
4. For this task, calling a foundation model through an API is better than training our own model because the foundation model is already trained on a large amount of data and can understand and generate natural language without requiring us to collect a large loan-application dataset or spend significant computing resources training a model. It also allowed us to build the system quickly using prompting. However, training our own model could be preferable when we have a large, high-quality domain-specific dataset, need more control over the model, require offline processing, or have strict privacy requirements that make sending data to an external API inappropriate.